upstream frontend_pool {

    server 192.168.56.11:80 weight=1 max_fails=3 fail_timeout=30s;
    server 192.168.56.12:80 weight=1 max_fails=3 fail_timeout=30s;
    keepalive 16;
}

server {
    listen 80;

    location / {
        proxy_pass          http://frontend_pool;
        proxy_http_version  1.1;
        proxy_set_header    Connection        "";
        proxy_set_header    Host              $host;
        proxy_set_header    X-Real-IP         $remote_addr;
        proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
