---
- name: Allow port 3001 from web servers
  ufw:
    rule: allow
    src: "{{ item }}"
    port: '3001'
    proto: tcp
    # web-server1/2 and ci-server
    # web-server1/2  requests API , ci-server checking state after deployment
  loop:
    - '192.168.56.11'
    - '192.168.56.12'
    - '192.168.56.15'

- name: Deploy backend container
  become_user: devops
  shell: |
    docker-compose -f docker-compose.backend.yml down --remove-orphans 2>/dev/null || true
    docker-compose -f docker-compose.backend.yml up -d --build
  args:
    chdir: /vagrant