---
# allow to work with HHTps repo
# GPG key  checker

- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker CE and docker-compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present

- name: Add devops to docker group
  user:
    name: devops
    groups: docker
    append: yes

- name: Enable and start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Configure insecure local registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["192.168.56.15:5000"]
      }
  notify: restart docker