# list of servers
# "Ansible_Local" bcs i'm working on windows  , ansible didn't work on windows
# as Control node . Vagrant setting up Ansible straight trought each VM's and
# and each VM's configures themselves
[all]
localhost ansible_connection=local